# Generated by Django 4.1.2 on 2022-10-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quizs_answersofparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizs',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
