# Generated by Django 4.1.2 on 2022-10-10 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_answersofparticipant_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_que', to='main.questions'),
        ),
        migrations.AlterField(
            model_name='answersofparticipant',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_que', to='main.questions'),
        ),
        migrations.AlterField(
            model_name='answersofparticipant',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_quizs', to='main.quizs'),
        ),
        migrations.AlterField(
            model_name='quizs',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizs_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
