# Generated by Django 4.1.2 on 2022-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_answers_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizs',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
